services:
  db:
    image: postgres:15-alpine
    container_name: backend_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-tms_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: backend_redis
    restart: always
    ports:
      - "6379:6379"

  libretranslate:
    image: libretranslate/libretranslate
    container_name: backend_translator
    ports:
      - "5000:5000"
    volumes:
      - lt_data:/home/libretranslate/.local # Persist translation data

  pgadmin:
    image: dpage/pgadmin4
    container_name: backend_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  minio:
    image: minio/minio:latest
    container_name: backend_minio
    restart: always
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  locust:
    image: locustio/locust
    container_name: backend_locust
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  minio_data:
  lt_data: