import logging
import celery
from app.worker.main import celery_app
from app.services.pdf_service import generate_translation_pdf_bytes
from app.db.session import SessionLocal
from app.models.translation import Translation
# Mandatory import to avoid SQLAlchemy "Mapper[Translation] failed to locate a name 'User'" error
from app.models.user import User  
from deep_translator import GoogleTranslator
from app.core.storage import upload_pdf_to_minio
from sqlalchemy.orm import joinedload

# Configure logging to see errors in Celery logs
logger = logging.getLogger(__name__)

@celery_app.task(
    name="process_pdf_task",
    bind=True,                # Allows access to task instance (self)
    max_retries=3,            # Retry up to 3 times if it fails
    default_retry_delay=2     # Wait 2 seconds between retries
)
def process_pdf_task(self, translation_id: int, pdf_data: dict):
    """
    Background task to handle text translation, PDF generation, 
    and storage in MinIO organized by user folders.
    """
    db = SessionLocal()
    translation = None
    
    try:
        # Fetch the translation record from the database
        translation = db.query(Translation).options(
            joinedload(Translation.owner)
        ).filter(Translation.id == translation_id).first()
        
        if not translation:
            logger.error(f"Translation ID {translation_id} not found in database.")
            return "Error: ID not found"

        if translation and translation.owner:
            # Metemos el email real en la caja que va al service
            pdf_data["user_email"] = translation.owner.email
        else:
            pdf_data["user_email"] = "N/A"
        
        # Sincronizamos el email del usuario en pdf_data
        pdf_data["user_email"] = translation.owner.email if translation.owner else "N/A"

        # 1. Sync data to ensure we have the latest info from the DB
        pdf_data["pdf_lang"] = translation.pdf_lang
        pdf_data["target_lang"] = translation.target_language

        # 2. Translation logic with retry for transient API issues
        try:
            # Check if we need to call the translation service
            if not translation.translated_text or translation.translated_text == "Translation Service Unavailable":
                logger.info(f"Translating ID {translation_id} via Google API...")
                translator = GoogleTranslator(
                    source=translation.source_lang.lower(), 
                    target=translation.target_language.lower()
                )
                translated = translator.translate(translation.original_text)
                
                if not translated:
                    raise ValueError("Translation returned empty result")

                translation.translated_text = translated
                pdf_data["translated_text"] = translated
                # Commit early so the text is saved even if PDF generation fails later
                db.commit() 
            
            else:
                # Reuse existing translation from DB
                logger.info(f"Reusing existing translation for ID {translation_id}")
                pdf_data["translated_text"] = translation.translated_text
            
        except Exception as e:
            logger.warning(f"Translation failed for ID {translation_id}: {e}")
            translation.status = "error"
            translation.translated_text = "Translation Service Unavailable"
            db.commit() 
            # Trigger Celery retry mechanism
            raise self.retry(exc=e)

        # 3. PDF Generation & MinIO Storage
        try:
            pdf_bytes = generate_translation_pdf_bytes(pdf_data)
        
            # Organize files in MinIO using a user-specific folder structure
            user_id = pdf_data.get("user_id", "unknown")
            file_name = f"user_{user_id}/translation_{translation_id}.pdf"
            
            # Upload the generated bytes to MinIO
            upload_pdf_to_minio(pdf_bytes, file_name)
            
            # Update database record with the final file path and status
            translation.file_path = file_name 
            translation.status = "completed"
            db.commit()
            
        except Exception as e:
            logger.error(f"PDF/Storage error for ID {translation_id}: {e}")
            translation.status = "error"
            db.commit()
            raise e 

        return f"Task finished successfully for ID {translation_id}"

    except Exception as e:
        db.rollback()
        # Handle Celery retries correctly to avoid marking the task as failed prematurely
        if isinstance(e, celery.exceptions.Retry):
            raise e
            
        # If an unhandled exception occurs, mark the record as error in DB
        if translation:
            translation.status = "error"
            db.commit()
        raise e 
    finally:
        # Always close the database session to prevent connection leaks
        db.close()