"""add_is_active_to_translations

Revision ID: 4daa5abf92d3
Revises: c783ba7bdef7
Create Date: 2026-04-27 11:32:30.350668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4daa5abf92d3'
down_revision: Union[str, Sequence[str], None] = 'c783ba7bdef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('translations', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    op.execute("UPDATE translations SET is_active = True")
    
    op.alter_column('translations', 'is_active', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translations', 'is_active')
    # ### end Alembic commands ###
