"""add_embedding_to_translations

Revision ID: cfe0aa840cf3
Revises: b7c2139e7ba0
Create Date: 2026-04-29 11:30:30.005970

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe0aa840cf3'
down_revision: Union[str, Sequence[str], None] = 'b7c2139e7ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translations', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translations', 'embedding')
    # ### end Alembic commands ###
