"""add_embedding_column

Revision ID: 0006_ec4e80e2313e
Revises: cfe0aa840cf3
Create Date: 2026-04-29 11:50:57.146015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006_ec4e80e2313e'
down_revision: Union[str, Sequence[str], None] = 'cfe0aa840cf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
