"""Fix column names

Revision ID: 242b8c767746
Revises: 0c5a208632c9
Create Date: 2026-03-03 09:43:42.504845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242b8c767746'
down_revision: Union[str, Sequence[str], None] = '0c5a208632c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translations', sa.Column('source_lang', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translations', 'source_lang')
    # ### end Alembic commands ###
