"""limit_original_text_length

Revision ID: c783ba7bdef7
Revises: 0c5a208632c9
Create Date: 2026-04-24 16:06:35.091696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c783ba7bdef7'
down_revision: Union[str, Sequence[str], None] = '0c5a208632c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translations', 'original_text',
               existing_type=sa.TEXT(),
               type_=sa.String(length=4500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('translations', 'original_text',
               existing_type=sa.String(length=4500),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
